name: Jfdev Ci Commons Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4
      -  run: |
          git config --global user.email "omri.zelinko@gmail.com"
          git config --global user.name "omrizel"
          timestamp=$(date +"%Y%m%d%H%M%S")
          git checkout -b milestone/${timestamp}-master
          echo "jfdev_ci_commons=${{ inputs.version }}" >> ${{ github.workspace }}/release.version
          git add ${{ github.workspace }}/release.version
          git commit -m "DEVF-502 - Update release versions"
          git push origin milestone/${timestamp}-master
  build:
    runs-on: ubuntu-latest
    needs: prepare-release
    steps:
      - name: Trigger Build
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: omrizel
          repo: omrizel/test-actions
          github_token: ${{ secrets.REPO_TOKEN }}
          workflow_file_name: jfdev-ci-commons-build.yml
          wait_workflow: true
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - uses: actions/checkout@v3
    #  - uses: jfrog/setup-jfrog-cli@v4
    #    env:
    #      JF_URL: ${{ secrets.PLATFORM_URL }}
    #      JF_ACCESS_TOKEN:  ${{ secrets.PLATFORM_ADMIN_TOKEN }}
    #  - name: Run a one-line script
    #    run: |
    #      echo "build - should always run"

      
