name: My Reusable Workflow

on:
  workflow_dispatch:

jobs:
  conditional-job:
    runs-on: ubuntu-latest
    if: 'contains(toJson(inputs.names), "John")'
    steps:
      - name: Conditional Step A
        run: echo "Step A executed because 'John' is in the names list"

  always-run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step B
        run: echo "Step B always runs"
