name: Caller Workflow
on:
  workflow_dispatch:
  jobs:
    build:
      uses: ./.github/workflows/reusable-workflow.yml
      with:
        names: '["John", "Jean"]'  # Or omit this line to print "bla"
